name: Publish

on:
   pull_request:
     branches:
       - release
   push:
     branches:
       - release

jobs:

  publish:
    runs-on: windows-latest
    strategy:
      matrix:
         dotnet: ['3.x', '5.x','6.x']
          
    steps:

    - name: Release Dll
      run : dotnet build -c Release

    - name: Pack - Env
      run: dotnet pack --include-symbols -p:SymbolPackageFormat=snupkg --no-build -c Release DotNetCore.Compile.Environment/DotNetCore.Compile.Environment.csproj -o .

    - name: Push to Nuget - Env
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
